tienda_electronica/administracion/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='administracion'

urlpatterns = [
    path('', views.index, name='index'),

    path('tiendas/', views.tiendas, name='tiendas'),
    path('crearTienda/', views.crearTienda, name='crearTienda'),
    path('productos/', views.productos, name='productos'),
    path('crearProducto/', views.crearProducto, name='crearProducto'),
    path('vendedores/', views.vendedores, name='vendedores'),
    path('crearVendedor/', views.crearVendedor, name='crearVendedor'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('crearOferta/', views.crearOferta, name='crearOferta'),
    
]

tienda_electronica/tienda/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='tienda'

urlpatterns = [
    path('', views.index, name='index'),

    path('ventas/', views.ventas, name='ventas'),
    path('crearVenta/', views.crearVenta, name='crearVenta'),
    
]

tienda_electronica/tienda_electronica/urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacion import views

urlpatterns = [

    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('', include('autenticacion.urls')),

    # path('admin/', admin.site.urls),
    path('administracion/', include('administracion.urls')),
    path('tienda/', include('tienda.urls')),

]

tienda_electronica/administracion/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Tienda(models.Model):
    CERRILLOS = 'Cerrillos'
    SANTIAGO = 'Santiago'

    COMUNA_CHOICES = (
        (CERRILLOS, 'cerrillos'),
        (SANTIAGO, 'Santiago')
    )
    nombre_tienda = models.CharField(max_length=200)
    direccion = models.CharField(max_length=200, default="")
    comuna = models.CharField(max_length=200, choices=COMUNA_CHOICES)
    telefono = models.IntegerField(default="")
    correo_electronico = models.CharField(max_length=200, default="")

    def __str__(self):
        return self.nombre_tienda


class Vendedor(AbstractUser):
    tienda = models.ForeignKey(Tienda, on_delete=models.CASCADE, null=True)
    administrador = models.BooleanField(default=False)

class Producto(models.Model):

    ABARROTES = 'Abarrotes'
    LIMPIEZA = 'Limpieza'
    VERDURAS = 'Verduras'

    TIPO_CHOICES = (
        (ABARROTES, 'Abarrotes'),
        (LIMPIEZA, 'Limpieza'),
        (VERDURAS, 'Verduras')
    )
    nombre_producto = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=200, default="")
    precio = models.IntegerField(null=True)
    tipo = models.CharField(max_length=200, choices=TIPO_CHOICES, default="")
    tienda = models.ForeignKey(Tienda, on_delete=models.CASCADE, default="")

    def __str__(self):
        return self.nombre_producto

        
class Oferta(models.Model):
    nombre_oferta = models.CharField(max_length=200)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)
    porc_descuento = models.IntegerField(null=True)

    def __str__(self):
        return self.nombre_oferta

tienda_electronica/tienda/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from administracion.models import *

# Create your models here.
class Venta(models.Model):
    vendedor = models.ForeignKey('administracion.vendedor', on_delete=models.CASCADE)
    fecha_venta =models.DateTimeField(default=timezone.now)
    subtotal = models.IntegerField(default=0)
    iva = models.IntegerField(default=0)
    total = models.IntegerField(default=0)

    def __str__(self):
        return self.vendedor.username

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.IntegerField(default=0)
    cantidad = models.IntegerField(default=0)
    subtotal = models.IntegerField(default=0)

    def __str__(self):
        return self.producto.nombre_producto

tienda_electronica/administracion/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from .models import Tienda, Oferta, Producto, Vendedor
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class TiendaForm(forms.ModelForm):
    class Meta():
        model = Tienda
        fields = ('nombre_tienda', 'direccion', 'comuna', 'telefono', 'correo_electronico',)
       

    def __init__(self, *args, **kwargs):
        super(TiendaForm, self).__init__(*args,**kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        

class ProductoForm(forms.ModelForm):
    class Meta():
        model = Producto
        fields = ('nombre_producto', 'descripcion', 'precio', 'tipo', 'tienda', )
       

    def __init__(self, *args, **kwargs):
        super(ProductoForm, self).__init__(*args,**kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        

class OfertaForm(forms.ModelForm):
    class Meta():
        model = Oferta
        fields = ('nombre_oferta', 'producto', 'porc_descuento', )
       

    def __init__(self, *args, **kwargs):
        super(OfertaForm, self).__init__(*args,**kwargs)
        
         
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        

class VendedorForm(UserCreationForm):
    class Meta:
        model = Vendedor
        fields = ('username', 'email', 'tienda', 'password1', 'password2', 'administrador' )

    def __init__(self, *args, **kwargs):
        super(VendedorForm, self).__init__(*args,**kwargs)
        
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        

tienda_electronica/tienda/forms.py
from django.forms import *
from django.utils import timezone
from .models import Venta

class VentaForm(ModelForm):
    class Meta():
        model = Venta
        fields = ('fecha_venta', 'iva', 'subtotal', 'total',)
        widgets = {
            'fecha_venta': DateInput(
                format='%Y-%m-%d',
                attrs={
                    'value': timezone.now().strftime('%Y-%m-%d')
                }
            ),
            'iva': TextInput(attrs={
                'class': 'form-control',
            }),
            'subtotal': TextInput(attrs={
                'readonly': True,
                'class': 'form-control',
            }),
            'total': TextInput(attrs={
                'readonly': True,
                'class': 'form-control',
            })
        }

    def __init__(self, *args, **kwargs):
        super(VentaForm, self).__init__(*args,**kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

tienda_electronica/administracion/views.py
from django.shortcuts import render
# from django.contrib.auth.models import User
from .models import Tienda, Producto, Vendedor, Oferta
from .forms import TiendaForm, ProductoForm, OfertaForm, VendedorForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.


def index(request):
    return render(request, 'administracion/index.html', {})


def crearTienda(request):
    if request.method == 'GET':
        tienda_form = TiendaForm()
        context = {
            'tienda_form': tienda_form
        }
        return render(request, 'administracion/crearTienda.html', context)

    elif request.method == 'POST':
        tienda_form = TiendaForm(data=request.POST)
        if tienda_form.is_valid():
            tienda_form.save()
            tienda = Tienda.objects.all()
            context = {'tienda': tienda}
            return render(request, 'administracion/tiendas.html', context)

        else:
            message = tienda_form.errors
        contexto = {
            'tienda_form': tienda_form,
        }
        return render(request, 'administracion/index.html', contexto)


def crearProducto(request):
    if request.method == 'GET':
        producto_form = ProductoForm()
        context = {
            'producto_form': producto_form
        }
        return render(request, 'administracion/crearProducto.html', context)

    elif request.method == 'POST':
        message = ''
        producto_form = ProductoForm(data=request.POST)
        if producto_form.is_valid():
            producto_form.save()
            producto = Producto.objects.all()
            context = {'producto': producto}
            return render(request, 'administracion/productos.html', context)
        else:
            message: producto_form.errors
            context = {
                'message': message,
                'producto_form': producto_form
            }
            return render(request, 'administracion/crearProducto.html', context)


def crearVendedor(request):
    if request.method == 'GET':
        vendedor_form = VendedorForm()
        context = {
            'vendedor_form': vendedor_form
        }
        return render(request, 'administracion/crearVendedor.html', context)

    elif request.method == 'POST':
        vendedor_form = VendedorForm(data=request.POST)
        if vendedor_form.is_valid():
            vendedor_form.save()
            vendedor = Vendedor.objects.all()
            context = {'vendedor': vendedor}
            return render(request, 'administracion/vendedores.html', context)
        else:
            message = vendedor_form.errors

        contexto = {
            'tienda_form': vendedor_form,
        }
        return render(request, 'administracion/vendedores.html', contexto)


def crearOferta(request):
    if request.method == 'GET':
        oferta_form = OfertaForm()
        context = {
            'oferta_form': oferta_form
        }
        return render(request, 'administracion/crearOferta.html', context)

    elif request.method == 'POST':
        message = ''
        oferta_form = OfertaForm(data=request.POST)
        if oferta_form.is_valid():
            oferta_form.save()
            oferta = Oferta.objects.all()
            context = {'oferta': oferta}
            return render(request, 'administracion/ofertas.html', context)
        else:
            message = oferta_form.errors

        contexto = {
            'tienda_form': oferta_form,
        }
        return render(request, 'administracion/ofertas.html', contexto)


def tiendas(request):
    if request.method == 'GET':
        tienda = Tienda.objects.all()
        context = {'tienda': tienda}
        return render(request, 'administracion/tiendas.html', context)


def vendedores(request):
    if request.method == 'GET':
        vendedor = Vendedor.objects.all()
        context = {'vendedor': vendedor}
        return render(request, 'administracion/vendedores.html', context)


def productos(request):
    if request.method == 'GET':
        producto = Producto.objects.all()
        context = {'producto': producto}
        return render(request, 'administracion/productos.html', context)


def ofertas(request):
    oferta = []
    if request.method == 'GET':
        if request.user.administrador:
            oferta = Oferta.objects.all()
        else:
            producto = Producto.objects.filter(tienda=request.user.tienda)
            for p in producto:
                if Oferta.objects.filter(producto_id=p.id):
                    for f in (Oferta.objects.filter(producto_id=p.id)):
                        oferta.append(f)
        context = {'oferta': oferta}
        return render(request, 'administracion/ofertas.html', context)

tienda_electronica/tienda/views.py
from django.shortcuts import render

from .models import Venta
from .forms import VentaForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.
def index(request):
    return render(request, 'tienda/index.html', {})


def crearVenta(request):
    if request.method == 'GET':
        venta_form = VentaForm()
        context = {
            'venta_form': venta_form
        }
        return render(request, 'tienda/crearVenta.html', context)

    elif request.method == 'POST':
        venta_form = VentaForm(data=request.POST)
        if venta_form.is_valid():
            venta_form.save()
            venta = Venta.objects.all()
            context = {'venta': venta}
            return render(request, 'tienda/ventas.html', context)

        else:
            message = venta_form.errors
        contexto = {
            'venta_form': venta_form,
        }
        return render(request, 'tienda/index.html', contexto)

def ventas(request):
    if request.method == 'GET':
        venta = Venta.objects.all()
        context = {'venta': venta}
        return render(request, 'tienda/ventas.html', context)

tienda_electronica/administracion/templates/administracion/crearOferta.html
{% extends 'base.html' %}

{% block title %}Nuevo Producto{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<section class='container'>
    <h1>{{ message }}</h1>
    {% if oferta %}

    <h1>{{ oferta.nombre_tienda }}</h1>
    <h1>{{ oferta.direccion }}</h1>

    {% endif %}

    <form action='{% url 'administracion:crearOferta' %}' method="POST">
        {% csrf_token %}
        {{ oferta_form.as_p }}
        <button type='submit' name="button" value="crear" class="btn btn-primary">Agregar</button>
    </form>
</section>

{% endblock %}

tienda_electronica/administracion/templates/administracion/crearProducto.html
{% extends 'base.html' %}

{% block title %}Nuevo Producto{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<section class='container'>
    <h1>{{ message }}</h1>
    {% if producto %}

    <h1>{{ producto.nombre_tienda }}</h1>
    <h1>{{ producto.direccion }}</h1>

    {% endif %}

    <form action='{% url 'administracion:crearProducto' %}' method="POST">
        {% csrf_token %}
        {{ producto_form.as_p }}
        <button type='submit' name="button" value="crear" class="btn btn-primary">Agregar</button>
    </form>
</section>

{% endblock %}

tienda_electronica/administracion/templates/administracion/crearTienda.html
{% extends 'base.html' %}

{% block title %}Nueva Tienda{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<section class='container'>
    <h1>{{ message }}</h1>
    {% if tienda %}

    <h1>{{ tienda.nombre_tienda }}</h1>
    <h1>{{ tienda.direccion }}</h1>

    {% endif %}

    <form action='{% url 'administracion:crearTienda' %}' method="POST">
        {% csrf_token %}
        {{ tienda_form.as_p }}
        <button type='submit' name="button" value="crear" class="btn btn-primary">Agregar</button>
    </form>
</section>

{% endblock %}

tienda_electronica/administracion/templates/administracion/crearVendedor.html
{% extends 'base.html' %}

{% block title %}Nuevo Vendedor{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<section class='container'>
    <h1>{{ message }}</h1>

    <form action='{% url 'administracion:crearVendedor' %}' method="POST">
        {% csrf_token %}
        {{ vendedor_form.as_p }}
        <button type='submit' name="button" value="crear" class="btn btn-primary">Agregar</button>
    </form>
</section>

{% endblock %}

tienda_electronica/administracion/templates/administracion/home.html
{% extends 'base.html' %}

{% block title %}Portada{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}
<h1>Tienda Electrónica</h1>
{% comment %} <span class="subheading">Desarrollador fullstack</span> {% endcomment %}
{% endblock %}

tienda_electronica/administracion/templates/administracion/index.html
{% extends 'base.html' %}

{% block title %}Portada{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<h4>Bienvenido {{user.username}}</h4>

{% endblock %}

tienda_electronica/administracion/templates/administracion/ofertas.html
{% extends 'base.html' %}

{% block title %}Ofertas{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<table class="table table-dark table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Producto</th>
        <th>Porcentaje</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for oferta in oferta %}
      <tr>
        <td>{{oferta.id}} </td>
        <td>{{oferta.nombre_oferta}}</td>
        <td>{{oferta.producto}}</td>
        <td>{{oferta.porc_descuento}}</td>
     <td><button class="btn btn-info btn-sm"               
            >EDITAR
            </button>
          </td>

        <td class="text-center">
            <a class="btn btn-danger btn-sm"
            >ELIMINAR
            </a>
          </td>
      </tr>
        {% endfor%}
    </tbody>
  </table>

   <div class="text-center">
        <a class="btn btn-info btn-sm mt-3" 
         href="{% url 'administracion:crearOferta' %}"
        >Agregar Nuevo</a>
      </div>


{% endblock %}

tienda_electronica/administracion/templates/administracion/productos.html
{% extends 'base.html' %}

{% block title %}Productos{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<table class="table table-dark table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Descr</th>
        <th scope="col">Precio</th>
        <th scope="col">Tipo</th>
        <th scope="col">Tienda</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for producto in producto %}
      <tr>
        <td>{{producto.id}} </td>
        <td>{{producto.nombre_producto}}</td>
        <td>{{producto.descripcion}}</td>
        <td>{{producto.precio}}</td>
        <td>{{producto.tipo}}</td>
        <td>{{producto.tienda}}</td>
         <td><button class="btn btn-info btn-sm"               
            >EDITAR
            </button>
          </td>

        <td class="text-center">
            <a class="btn btn-danger btn-sm"
            >ELIMINAR
            </a>
          </td>
      </tr>
        {% endfor%}
    </tbody>
  </table>

   <div class="text-center">
        <a class="btn btn-info btn-sm mt-3" 
         href="{% url 'administracion:crearProducto' %}"
        >Agregar Nuevo</a>
      </div>


{% endblock %}

tienda_electronica/administracion/templates/administracion/tiendas.html
{% extends 'base.html' %}

{% block title %}Tiendas{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<table class="table table-dark table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Dirección</th>
        <th>Ciudad</th>
        <th>Comuna</th>
        <th>Teléfono</th>
        <th>Correo</th>
      </tr>
    </thead>
    <tbody>
      {% for tienda in tienda %}
      <tr>
        <td>{{tienda.id}} </td>
        <td>{{tienda.nombre_tienda}}</td>
        <td>{{tienda.direccion}}</td>
        <td>{{tienda.ciudad}}</td>
        <td>{{tienda.comuna}}</td>
        <td>{{tienda.telefono}}</td>
        <td>{{tienda.correo_electronico}}</td>
     <td><button class="btn btn-info btn-sm"               
            >EDITAR
            </button>
          </td>

        <td class="text-center">
            <a class="btn btn-danger btn-sm"
            >ELIMINAR
            </a>
          </td>
      </tr>
        {% endfor%}
    </tbody>
  </table>

   <div class="text-center">
        <a class="btn btn-info btn-sm mt-3" 
         href="{% url 'administracion:crearTienda' %}"
        >Agregar Nuevo</a>
      </div>


{% endblock %}

tienda_electronica/administracion/templates/administracion/vendedores.html
{% extends 'base.html' %}

{% block title %}Vendedores{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<table class="table table-dark table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre</th>
        <th>Tienda</th>
      </tr>
    </thead>
    <tbody>
      {% for vendedor in vendedor %}
      <tr>
        <td>{{vendedor.id}} </td>
        <td>{{vendedor.username}}</td>
        <td>{{vendedor.tienda}}</td>
   <td><button class="btn btn-info btn-sm"               
            >EDITAR
            </button>
          </td>

        <td class="text-center">
            <a class="btn btn-danger btn-sm"
            >ELIMINAR
            </a>
          </td>
      </tr>
        {% endfor%}
    </tbody>
  </table>

   <div class="text-center">
        <a class="btn btn-info btn-sm mt-3" 
         href="{% url 'administracion:crearVendedor' %}"
        >Agregar Nuevo</a>
      </div>


{% endblock %}