tienda_electronica/tienda/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='tienda'

urlpatterns = [
    path('', views.index, name='index'),

    path('ventas/', views.ventas, name='ventas'),
    path('crearVenta/', views.crearVenta, name='crearVenta'),
    
]

tienda_electronica/tienda_electronica/urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacion import views

urlpatterns = [

    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('', include('autenticacion.urls')),

    # path('admin/', admin.site.urls),
    path('administracion/', include('administracion.urls')),
    path('tienda/', include('tienda.urls')),

]

tienda_electronica/tienda/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from administracion.models import *

# Create your models here.
class Venta(models.Model):
    vendedor = models.ForeignKey('administracion.vendedor', on_delete=models.CASCADE)
    fecha_venta =models.DateTimeField(default=timezone.now)
    subtotal = models.IntegerField(default=0)
    iva = models.IntegerField(default=0)
    total = models.IntegerField(default=0)

    def __str__(self):
        return self.vendedor.username

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.IntegerField(default=0)
    cantidad = models.IntegerField(default=0)
    subtotal = models.IntegerField(default=0)

    def __str__(self):
        return self.producto.nombre_producto

tienda_electronica/tienda/forms.py
from django.forms import *
from django.utils import timezone
from .models import Venta

class VentaForm(ModelForm):
    class Meta():
        model = Venta
        fields = ('fecha_venta', 'iva', 'subtotal', 'total',)
        widgets = {
            'fecha_venta': DateInput(
                format='%Y-%m-%d',
                attrs={
                    'value': timezone.now().strftime('%Y-%m-%d')
                }
            ),
            'iva': TextInput(attrs={
                'class': 'form-control',
            }),
            'subtotal': TextInput(attrs={
                'readonly': True,
                'class': 'form-control',
            }),
            'total': TextInput(attrs={
                'readonly': True,
                'class': 'form-control',
            })
        }

    def __init__(self, *args, **kwargs):
        super(VentaForm, self).__init__(*args,**kwargs)
        
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

tienda_electronica/tienda/views.py
from django.shortcuts import render

from .models import Venta
from .forms import VentaForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.
def index(request):
    return render(request, 'tienda/index.html', {})


def crearVenta(request):
    if request.method == 'GET':
        venta_form = VentaForm()
        context = {
            'venta_form': venta_form
        }
        return render(request, 'tienda/crearVenta.html', context)

    elif request.method == 'POST':
        venta_form = VentaForm(data=request.POST)
        if venta_form.is_valid():
            venta_form.save()
            venta = Venta.objects.all()
            context = {'venta': venta}
            return render(request, 'tienda/ventas.html', context)

        else:
            message = venta_form.errors
        contexto = {
            'venta_form': venta_form,
        }
        return render(request, 'tienda/index.html', contexto)

def ventas(request):
    if request.method == 'GET':
        venta = Venta.objects.all()
        context = {'venta': venta}
        return render(request, 'tienda/ventas.html', context)

tienda_electronica/tienda/templates/tienda/crearVenta.html
{% extends 'base.html' %}

{% block title %}Nueva Venta{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<section class='container'>
    <h1>{{ message }}</h1>
    {% if venta %}

    <h1>{{ venta.vendedor }}</h1>
    <h1>{{ venta.fecha_venta }}</h1>

    {% endif %}

    <form action='{% url 'tienda:crearVenta' %}' method="POST">
        {% csrf_token %}
        {{ venta_form.as_p }}
        <button type='submit' name="button" value="crear" class="btn btn-primary">Agregar</button>
    </form>
</section>

{% endblock %}

tienda_electronica/tienda/templates/tienda/index.html
{% extends 'base.html' %}

{% block title %}Portada{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<h4>Bienvenido {{user.username}}</h4>

{% endblock %}

tienda_electronica/tienda/templates/tienda/ventas.html
{% extends 'base.html' %}

{% block title %}Ventas{% endblock %}

{% block background %}{% load static %}{% static 'core/img/home-bg.jpg' %}{% endblock %}

{% block headers %}

<table class="table table-dark table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th>ID</th>
        <th>Vendedor</th>
        <th>Subtotal</th>
        <th>IVA</th>
        <th>Total</th>
        <th>Productos</th>
      </tr>
    </thead>
    <tbody>
      {% for venta in venta %}
      <tr>
        <td>{{venta.id}} </td>
        <td>{{venta.vendedor}}</td>
        <td>{{venta.subtotal}}</td>
        <td>{{venta.iva}}</td>
        <td>{{venta.total}}</td>
        <td>{{venta.producto}}</td>
     <td><button class="btn btn-info btn-sm"               
            >EDITAR
            </button>
          </td>

        <td class="text-center">
            <a class="btn btn-danger btn-sm"
            >ELIMINAR
            </a>
          </td>
      </tr>
        {% endfor%}
    </tbody>
  </table>

   <div class="text-center">
        <a class="btn btn-info btn-sm mt-3" 
         href="{% url 'tienda:crearVenta' %}"
        >Agregar Nuevo</a>
      </div>


{% endblock %}