tienda_electronica/administracion/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='administracion'

urlpatterns = [
    path('', views.index, name='index'),

    path('tiendas/', views.tiendas, name='tiendas'),
    path('crearTienda/', views.crearTienda, name='crearTienda'),
    path('productos/', views.productos, name='productos'),
    path('crearProducto/', views.crearProducto, name='crearProducto'),
    path('vendedores/', views.vendedores, name='vendedores'),
    path('crearVendedor/', views.crearVendedor, name='crearVendedor'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('crearOferta/', views.crearOferta, name='crearOferta'),
    
]

tienda_electronica/autenticacion/urls.py
from django.urls import path
from .views import *

app_name = 'autenticacion'

urlpatterns = [

    # path('', include('django.contrib.auth.urls'))
    path('logout/', logout, name='logout'),
    path('login/', login, name='login'),
]

tienda_electronica/tienda/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='tienda'

urlpatterns = [
    path('', views.index, name='index'),

    path('ventas/', views.ventas, name='ventas'),
    path('crearVenta/', views.crearVenta, name='crearVenta'),
    
]

tienda_electronica/tienda_electronica/urls.py
from django.contrib import admin
from django.urls import path, include
from autenticacion import views

urlpatterns = [

    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('', include('autenticacion.urls')),

    # path('admin/', admin.site.urls),
    path('administracion/', include('administracion.urls')),
    path('tienda/', include('tienda.urls')),

]

tienda_electronica/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{%block title%}{% endblock %} | GARESOFT</title>

<head>
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/custom.css' %}" rel="stylesheet">
</head>

 <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
       <a class="navbar-brand" href="{% url 'home' %}">GARESOFT</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menú
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          {% if not user.is_authenticated %}      
            <li class="nav-item">
              <a class="nav-link" href="{% url 'autenticacion:login' %}">Iniciar sesión</a>
            </li>
            {% else %}
          {% if not user.administrador %}    
            <li class="nav-item">
              <a class="nav-link" href="{% url 'administracion:ofertas' %}">Ofertas</a>
            </li>            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tienda:ventas' %}">Ventas</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{% url 'autenticacion:logout' %}">Cerrar Sesión</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'administracion:tiendas' %}">Tiendas</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="{% url 'administracion:vendedores' %}">Vendedores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'administracion:productos' %}">Productos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'administracion:ofertas' %}">Ofertas</a>
            </li>
             
            <li class="nav-item">
              <a class="nav-link" href="{% url 'autenticacion:logout' %}">Cerrar Sesión</a>
            </li>
             {% endif %}
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    <!-- Cabecera -->
    <header class="masthead" style="background-image: url('{% block background %}{% endblock %}')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              {% block headers %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
    </header>

    {% block content %}
    {% endblock %}
    
<!-- Pié de página -->
    <footer>
    {{ user.is_authenticated}}
    {{ user.username}}
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-youtube fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; 2020 · garesoft </p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap y Javascripts -->
    <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/clean-blog.min.js' %}"></script>

  </body>

</html>